rozo_scan: use rozodiag instead of crm to find out the active export host

diff --git a/src/rozofsmount/rozo_scan b/src/rozofsmount/rozo_scan
--- a/src/rozofsmount/rozo_scan
+++ b/src/rozofsmount/rozo_scan
@@ -119,16 +119,20 @@ if [ "${local}" == "YES" ]
 then
   active="$HOSTNAME"
 else
-  for export in `echo $exports | tr \/ ' '`
+  for active in `echo $exports | tr \/ ' '`
   do
-    active=`ssh ${export} "crm_resource --resource p-fs-exportd --locate -Q"`
-    if [ $? -ne 0 ];
-    then
-      active=""
-      continue
-    fi 
-    break
+    rozodiag -i ${active} -T export:0 -c up | grep uptime >> /dev/null
+    case "$?" in
+      "0") break;;
+      *)   active="";;
+    esac      
   done
+  case "${active}" in
+    "") {
+      echo "Active exportd not found within ${exports}"
+      exit 1
+    };;
+   esac   
 fi
 #
 # At least one parameter should be provided 
